name: Update files

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Update files
        uses: MathieuSoysal/file-updater-for-release@v1.0.1
        with:
          prefix: "file-updater-for-release@" # Prefix before the version, default is: ""

      - uses: EndBug/add-and-commit@v9
        with:
          add: .
          default_author: github_actions
          message: "Update files"
          push: true
          token: ${{ inputs.repo-token }}
