name: Update files

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Update files
        uses: MathieuSoysal/file-updater-for-release@v1.0.1
        with:
          prefix: "file-updater-for-release@" # Prefix before the version, default is: ""
          repo-token: ${{ secrets.REPO_TOKEN }} # The token to use to commit the changes

