name: Test Actions locally

on: [workflow_dispatch]

jobs:
  check-files: # Check the files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: GuillaumeFalourd/assert-command-line-output@v2
        with:
          command_line: cat tests/test1.txt
          contains: JAVAVER/SIONv1.2.3JAVAVERSION

      - uses: GuillaumeFalourd/assert-command-line-output@v2
        with:
          command_line: cat tests/test2.txt
          contains: JAVAVER/SIONv1.2.3JAVAVERSION

  test-for-github-workflow: # Test the action with the GitHub workflow
    name: Test update-readme-files action
    needs: check-files
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update files
        uses: ./
        with:
          files: tests/test1.txt tests/test2.txt
          version: "v2.0.0"
          old-version: "v1.2.3"
          prefix: "JAVAVER/SION"
          suffix: "JAVAVERSION"
          with-commit: false

      - name: Test if file 1 have been updated
        uses: GuillaumeFalourd/assert-command-line-output@v2
        with:
          command_line: cat tests/test1.txt
          contains: JAVAVER/SIONv2.0.0JAVAVERSION

      - name: Test if file 2 have been updated
        uses: GuillaumeFalourd/assert-command-line-output@v2
        with:
          command_line: cat tests/test2.txt
          contains: JAVAVER/SIONv2.0.0JAVAVERSION
